//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputAction/CommunicationUI.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CommunicationUI: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CommunicationUI()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CommunicationUI"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""9ed7bc28-4126-41d3-b7ae-aa7bf7830d18"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""91f5f0e9-9b2b-4429-a485-c311a2eee297"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""75cff448-a9a4-4c90-9c14-6df1316d262d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cansel"",
                    ""type"": ""Button"",
                    ""id"": ""1023cc20-ceef-4971-8e9c-0bb3ce48b944"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Match"",
                    ""type"": ""Button"",
                    ""id"": ""65147556-3f97-4f3a-b273-a49d3c06c58b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GameStart"",
                    ""type"": ""Button"",
                    ""id"": ""2fd5bb16-6194-41de-9891-aad40208d2f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""612fe12b-d4e0-4256-8092-7e86e79ffbf1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f698a675-245b-4f99-a441-2d380d870d87"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""140bd9d3-7d70-42d6-8ddd-82b1c7e31843"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0f570bc4-a691-4c7d-bd2b-6596c39455d5"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ff525e66-6c53-47f9-9389-f1c80d574217"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cansel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16aa5a50-8162-41b1-924f-b8d8cd2dbd58"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Match"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ddb09fd-ef01-4839-a125-8b92cecdc413"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GameStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""id"": ""334e1fcd-8a78-4bde-ad7f-3f8441184f4e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ff8be0ed-05bf-48bb-955b-38de1320f1a4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""07bf4886-b273-4d38-a811-2b41e81d6faf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""5c33a0f6-0a2a-4e6c-a45b-34034b884d06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f4223210-1d50-46d9-9ebe-73f89e9eaab9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""10a30d9a-f0d0-499b-94db-75783d865ebf"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4b53f8e9-ebbb-4df0-a81a-123c5db71f3d"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9e492a64-9029-4cdb-a83c-26b1ebf8ee7a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""06bcd3f7-8862-4d0a-ab7d-f91540b71540"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""078b2067-3f01-43e3-8cdb-40816601023c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ad80999-d9ea-4e06-8908-f36d57626faa"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CharSelect"",
            ""id"": ""30a2aba2-5ca5-4259-ba7e-e5c5d3938609"",
            ""actions"": [
                {
                    ""name"": ""Right"",
                    ""type"": ""Value"",
                    ""id"": ""647196c3-db86-4a78-aced-d3cb2fdbb1bb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Value"",
                    ""id"": ""64485418-f12f-478e-8593-378bbb7bce0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""d24a02f4-2f71-44be-af35-6b8b2e3acc86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0dcb8225-276b-4209-b2df-38153c4fa40c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ca056a47-f3d3-4374-aad6-de1316c1c540"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""304824aa-9454-476f-ae49-2b276df9690d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""80668a1c-b2e4-4207-8fe1-0e956e7d8a7c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4fbfa577-c979-4509-8193-9ecf9355e517"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""StageSelect"",
            ""id"": ""988fc3bf-5385-43df-9526-4256ed78e5c7"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""d29a8fd1-d27b-425b-b8f1-c43789e765f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""3ad93c7f-b79d-4384-a5a1-844702f59b3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""6eb1e988-69e1-4532-9db2-2ad880a28c6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""4e307be3-9749-4251-91ff-c4e7b4521971"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""ec12d3ed-03ae-4090-bafc-9a88d4171e9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""339bc616-b625-4b0d-8838-e1ca048c0e30"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85fd7596-5bbf-4035-811c-1e4ea69233fa"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cfe57d1-11e1-45eb-8f33-7867599d4b2b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14c40792-25b1-49b6-9b4b-0bdc2f8d8f56"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d153148f-7c69-497a-859d-1b6789ece85e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""9c13ac6a-00cc-4db4-8373-40e9a536dfc6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2da852ce-1905-46ee-8a8b-b4f685cd97fd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b7a2535a-b5fc-41dc-b10e-606a7257c7d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tama"",
                    ""type"": ""Button"",
                    ""id"": ""368ebb5e-5c3d-4497-8c9d-78598e2a50dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""cf48efb0-8b52-47f2-91e3-5cd5054dcd1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9b578541-9dc6-4ff9-89c4-1641a6b30ffb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5afa2d67-12fa-4def-8c2b-290bd123e6b3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dd48f219-9315-407c-a260-75d80e678347"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d09d563f-7ea7-40ff-8def-dfbef8c0e465"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f56200e4-9674-4647-a1a9-f097c6b0ddde"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tama"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""990bcf98-d8a2-41fe-8b49-c3290d3733b2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GameClear"",
            ""id"": ""8aaa8218-4ebb-4ccd-ba71-ce8188ff7ef0"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""3bd9e1f0-e351-4ed2-b1eb-35d7ad3d18bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""c1be7f89-bfaa-4a01-89c8-1c7bb81bca61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""f11edc8c-e8d2-4040-9898-143983e1ea38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b49da02a-82dc-4688-882c-2e4665b08203"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b35d57bc-0bb4-4e7e-a37b-a424d7da508a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ca1224b-46ec-4e82-aa4c-0eb700896d87"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Tital"",
            ""id"": ""4e980044-b794-4289-a632-b0d03df4ff03"",
            ""actions"": [
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""fe17da48-fdae-4d88-91d2-0e07ad81297f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d77e7301-5dce-471a-b0c1-1d28667c008f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SecondMenu"",
            ""id"": ""8b0bf378-acfc-4875-bf66-97141c984859"",
            ""actions"": [
                {
                    ""name"": ""Maps"",
                    ""type"": ""Value"",
                    ""id"": ""8700a4a7-b186-42cb-bcde-930bada38dc4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""24dcd1df-28cd-4940-8d12-ee6626688acb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Navigate"",
                    ""id"": ""5634f181-62af-46c7-81e3-884fe4b00f0c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""02d07f2f-5abb-4da0-bbe0-7eaa6092a3fb"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""bb295e13-62b8-4915-a4e0-be58f4ade1d0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c298a495-3bf3-48d5-b23b-8ca0b70ff781"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FinalMenu"",
            ""id"": ""ebe05352-d39e-4b9f-9aac-1597e33499b5"",
            ""actions"": [
                {
                    ""name"": ""Maps"",
                    ""type"": ""Value"",
                    ""id"": ""8d7258d5-dedc-41fa-ab50-88af5929da63"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""345e6977-38db-481e-96d8-14ea6d49347a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9ce3944f-c009-4d69-a521-bdd7f70e8ac3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""id"": ""5e8293dd-b73e-4957-82f6-b3a119b59ebb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f8690b89-338c-4b03-98d4-e16a5e5094c5"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""17dfd562-8429-4660-bfe5-3ccbef183fc6"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Maps"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Move = m_UI.FindAction("Move", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cansel = m_UI.FindAction("Cansel", throwIfNotFound: true);
        m_UI_Match = m_UI.FindAction("Match", throwIfNotFound: true);
        m_UI_GameStart = m_UI.FindAction("GameStart", throwIfNotFound: true);
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_Move = m_Keyboard.FindAction("Move", throwIfNotFound: true);
        m_Keyboard_Submit = m_Keyboard.FindAction("Submit", throwIfNotFound: true);
        m_Keyboard_Back = m_Keyboard.FindAction("Back", throwIfNotFound: true);
        // CharSelect
        m_CharSelect = asset.FindActionMap("CharSelect", throwIfNotFound: true);
        m_CharSelect_Right = m_CharSelect.FindAction("Right", throwIfNotFound: true);
        m_CharSelect_Left = m_CharSelect.FindAction("Left", throwIfNotFound: true);
        m_CharSelect_Submit = m_CharSelect.FindAction("Submit", throwIfNotFound: true);
        // StageSelect
        m_StageSelect = asset.FindActionMap("StageSelect", throwIfNotFound: true);
        m_StageSelect_Up = m_StageSelect.FindAction("Up", throwIfNotFound: true);
        m_StageSelect_Down = m_StageSelect.FindAction("Down", throwIfNotFound: true);
        m_StageSelect_Left = m_StageSelect.FindAction("Left", throwIfNotFound: true);
        m_StageSelect_Right = m_StageSelect.FindAction("Right", throwIfNotFound: true);
        m_StageSelect_Submit = m_StageSelect.FindAction("Submit", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Tama = m_Player.FindAction("Tama", throwIfNotFound: true);
        m_Player_Menu = m_Player.FindAction("Menu", throwIfNotFound: true);
        // GameClear
        m_GameClear = asset.FindActionMap("GameClear", throwIfNotFound: true);
        m_GameClear_Up = m_GameClear.FindAction("Up", throwIfNotFound: true);
        m_GameClear_Down = m_GameClear.FindAction("Down", throwIfNotFound: true);
        m_GameClear_Submit = m_GameClear.FindAction("Submit", throwIfNotFound: true);
        // Tital
        m_Tital = asset.FindActionMap("Tital", throwIfNotFound: true);
        m_Tital_Submit = m_Tital.FindAction("Submit", throwIfNotFound: true);
        // SecondMenu
        m_SecondMenu = asset.FindActionMap("SecondMenu", throwIfNotFound: true);
        m_SecondMenu_Maps = m_SecondMenu.FindAction("Maps", throwIfNotFound: true);
        m_SecondMenu_Submit = m_SecondMenu.FindAction("Submit", throwIfNotFound: true);
        // FinalMenu
        m_FinalMenu = asset.FindActionMap("FinalMenu", throwIfNotFound: true);
        m_FinalMenu_Maps = m_FinalMenu.FindAction("Maps", throwIfNotFound: true);
        m_FinalMenu_Submit = m_FinalMenu.FindAction("Submit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Move;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cansel;
    private readonly InputAction m_UI_Match;
    private readonly InputAction m_UI_GameStart;
    public struct UIActions
    {
        private @CommunicationUI m_Wrapper;
        public UIActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_UI_Move;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cansel => m_Wrapper.m_UI_Cansel;
        public InputAction @Match => m_Wrapper.m_UI_Match;
        public InputAction @GameStart => m_Wrapper.m_UI_GameStart;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Cansel.started += instance.OnCansel;
            @Cansel.performed += instance.OnCansel;
            @Cansel.canceled += instance.OnCansel;
            @Match.started += instance.OnMatch;
            @Match.performed += instance.OnMatch;
            @Match.canceled += instance.OnMatch;
            @GameStart.started += instance.OnGameStart;
            @GameStart.performed += instance.OnGameStart;
            @GameStart.canceled += instance.OnGameStart;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Cansel.started -= instance.OnCansel;
            @Cansel.performed -= instance.OnCansel;
            @Cansel.canceled -= instance.OnCansel;
            @Match.started -= instance.OnMatch;
            @Match.performed -= instance.OnMatch;
            @Match.canceled -= instance.OnMatch;
            @GameStart.started -= instance.OnGameStart;
            @GameStart.performed -= instance.OnGameStart;
            @GameStart.canceled -= instance.OnGameStart;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
    private readonly InputAction m_Keyboard_Move;
    private readonly InputAction m_Keyboard_Submit;
    private readonly InputAction m_Keyboard_Back;
    public struct KeyboardActions
    {
        private @CommunicationUI m_Wrapper;
        public KeyboardActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Keyboard_Move;
        public InputAction @Submit => m_Wrapper.m_Keyboard_Submit;
        public InputAction @Back => m_Wrapper.m_Keyboard_Back;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(IKeyboardActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);

    // CharSelect
    private readonly InputActionMap m_CharSelect;
    private List<ICharSelectActions> m_CharSelectActionsCallbackInterfaces = new List<ICharSelectActions>();
    private readonly InputAction m_CharSelect_Right;
    private readonly InputAction m_CharSelect_Left;
    private readonly InputAction m_CharSelect_Submit;
    public struct CharSelectActions
    {
        private @CommunicationUI m_Wrapper;
        public CharSelectActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right => m_Wrapper.m_CharSelect_Right;
        public InputAction @Left => m_Wrapper.m_CharSelect_Left;
        public InputAction @Submit => m_Wrapper.m_CharSelect_Submit;
        public InputActionMap Get() { return m_Wrapper.m_CharSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharSelectActions set) { return set.Get(); }
        public void AddCallbacks(ICharSelectActions instance)
        {
            if (instance == null || m_Wrapper.m_CharSelectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharSelectActionsCallbackInterfaces.Add(instance);
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(ICharSelectActions instance)
        {
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(ICharSelectActions instance)
        {
            if (m_Wrapper.m_CharSelectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharSelectActions instance)
        {
            foreach (var item in m_Wrapper.m_CharSelectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharSelectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharSelectActions @CharSelect => new CharSelectActions(this);

    // StageSelect
    private readonly InputActionMap m_StageSelect;
    private List<IStageSelectActions> m_StageSelectActionsCallbackInterfaces = new List<IStageSelectActions>();
    private readonly InputAction m_StageSelect_Up;
    private readonly InputAction m_StageSelect_Down;
    private readonly InputAction m_StageSelect_Left;
    private readonly InputAction m_StageSelect_Right;
    private readonly InputAction m_StageSelect_Submit;
    public struct StageSelectActions
    {
        private @CommunicationUI m_Wrapper;
        public StageSelectActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_StageSelect_Up;
        public InputAction @Down => m_Wrapper.m_StageSelect_Down;
        public InputAction @Left => m_Wrapper.m_StageSelect_Left;
        public InputAction @Right => m_Wrapper.m_StageSelect_Right;
        public InputAction @Submit => m_Wrapper.m_StageSelect_Submit;
        public InputActionMap Get() { return m_Wrapper.m_StageSelect; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StageSelectActions set) { return set.Get(); }
        public void AddCallbacks(IStageSelectActions instance)
        {
            if (instance == null || m_Wrapper.m_StageSelectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StageSelectActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(IStageSelectActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(IStageSelectActions instance)
        {
            if (m_Wrapper.m_StageSelectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStageSelectActions instance)
        {
            foreach (var item in m_Wrapper.m_StageSelectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StageSelectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StageSelectActions @StageSelect => new StageSelectActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Tama;
    private readonly InputAction m_Player_Menu;
    public struct PlayerActions
    {
        private @CommunicationUI m_Wrapper;
        public PlayerActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Tama => m_Wrapper.m_Player_Tama;
        public InputAction @Menu => m_Wrapper.m_Player_Menu;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Tama.started += instance.OnTama;
            @Tama.performed += instance.OnTama;
            @Tama.canceled += instance.OnTama;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Tama.started -= instance.OnTama;
            @Tama.performed -= instance.OnTama;
            @Tama.canceled -= instance.OnTama;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // GameClear
    private readonly InputActionMap m_GameClear;
    private List<IGameClearActions> m_GameClearActionsCallbackInterfaces = new List<IGameClearActions>();
    private readonly InputAction m_GameClear_Up;
    private readonly InputAction m_GameClear_Down;
    private readonly InputAction m_GameClear_Submit;
    public struct GameClearActions
    {
        private @CommunicationUI m_Wrapper;
        public GameClearActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_GameClear_Up;
        public InputAction @Down => m_Wrapper.m_GameClear_Down;
        public InputAction @Submit => m_Wrapper.m_GameClear_Submit;
        public InputActionMap Get() { return m_Wrapper.m_GameClear; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameClearActions set) { return set.Get(); }
        public void AddCallbacks(IGameClearActions instance)
        {
            if (instance == null || m_Wrapper.m_GameClearActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameClearActionsCallbackInterfaces.Add(instance);
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(IGameClearActions instance)
        {
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(IGameClearActions instance)
        {
            if (m_Wrapper.m_GameClearActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameClearActions instance)
        {
            foreach (var item in m_Wrapper.m_GameClearActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameClearActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameClearActions @GameClear => new GameClearActions(this);

    // Tital
    private readonly InputActionMap m_Tital;
    private List<ITitalActions> m_TitalActionsCallbackInterfaces = new List<ITitalActions>();
    private readonly InputAction m_Tital_Submit;
    public struct TitalActions
    {
        private @CommunicationUI m_Wrapper;
        public TitalActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Submit => m_Wrapper.m_Tital_Submit;
        public InputActionMap Get() { return m_Wrapper.m_Tital; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TitalActions set) { return set.Get(); }
        public void AddCallbacks(ITitalActions instance)
        {
            if (instance == null || m_Wrapper.m_TitalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TitalActionsCallbackInterfaces.Add(instance);
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(ITitalActions instance)
        {
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(ITitalActions instance)
        {
            if (m_Wrapper.m_TitalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITitalActions instance)
        {
            foreach (var item in m_Wrapper.m_TitalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TitalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TitalActions @Tital => new TitalActions(this);

    // SecondMenu
    private readonly InputActionMap m_SecondMenu;
    private List<ISecondMenuActions> m_SecondMenuActionsCallbackInterfaces = new List<ISecondMenuActions>();
    private readonly InputAction m_SecondMenu_Maps;
    private readonly InputAction m_SecondMenu_Submit;
    public struct SecondMenuActions
    {
        private @CommunicationUI m_Wrapper;
        public SecondMenuActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Maps => m_Wrapper.m_SecondMenu_Maps;
        public InputAction @Submit => m_Wrapper.m_SecondMenu_Submit;
        public InputActionMap Get() { return m_Wrapper.m_SecondMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SecondMenuActions set) { return set.Get(); }
        public void AddCallbacks(ISecondMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_SecondMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SecondMenuActionsCallbackInterfaces.Add(instance);
            @Maps.started += instance.OnMaps;
            @Maps.performed += instance.OnMaps;
            @Maps.canceled += instance.OnMaps;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(ISecondMenuActions instance)
        {
            @Maps.started -= instance.OnMaps;
            @Maps.performed -= instance.OnMaps;
            @Maps.canceled -= instance.OnMaps;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(ISecondMenuActions instance)
        {
            if (m_Wrapper.m_SecondMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISecondMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_SecondMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SecondMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SecondMenuActions @SecondMenu => new SecondMenuActions(this);

    // FinalMenu
    private readonly InputActionMap m_FinalMenu;
    private List<IFinalMenuActions> m_FinalMenuActionsCallbackInterfaces = new List<IFinalMenuActions>();
    private readonly InputAction m_FinalMenu_Maps;
    private readonly InputAction m_FinalMenu_Submit;
    public struct FinalMenuActions
    {
        private @CommunicationUI m_Wrapper;
        public FinalMenuActions(@CommunicationUI wrapper) { m_Wrapper = wrapper; }
        public InputAction @Maps => m_Wrapper.m_FinalMenu_Maps;
        public InputAction @Submit => m_Wrapper.m_FinalMenu_Submit;
        public InputActionMap Get() { return m_Wrapper.m_FinalMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FinalMenuActions set) { return set.Get(); }
        public void AddCallbacks(IFinalMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_FinalMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FinalMenuActionsCallbackInterfaces.Add(instance);
            @Maps.started += instance.OnMaps;
            @Maps.performed += instance.OnMaps;
            @Maps.canceled += instance.OnMaps;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
        }

        private void UnregisterCallbacks(IFinalMenuActions instance)
        {
            @Maps.started -= instance.OnMaps;
            @Maps.performed -= instance.OnMaps;
            @Maps.canceled -= instance.OnMaps;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
        }

        public void RemoveCallbacks(IFinalMenuActions instance)
        {
            if (m_Wrapper.m_FinalMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFinalMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_FinalMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FinalMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FinalMenuActions @FinalMenu => new FinalMenuActions(this);
    public interface IUIActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCansel(InputAction.CallbackContext context);
        void OnMatch(InputAction.CallbackContext context);
        void OnGameStart(InputAction.CallbackContext context);
    }
    public interface IKeyboardActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface ICharSelectActions
    {
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
    public interface IStageSelectActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnTama(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
    public interface IGameClearActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
    public interface ITitalActions
    {
        void OnSubmit(InputAction.CallbackContext context);
    }
    public interface ISecondMenuActions
    {
        void OnMaps(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
    public interface IFinalMenuActions
    {
        void OnMaps(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
    }
}
